//
// https://newsapi.org/v2/top-headlines?country=eg&apiKey=bb828cd18aeb42f5afb50e816a05215f
//https://newsapi.org/v2/everything?q=tesla&apiKey=bb828cd18aeb42f5afb50e816a05215f

/*{
"status": "ok",
"totalResults": 34,
-"articles": [
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "اليوم السابع",
"title": "البنك المركزى المصرى يحسم اليوم أسعار الفائدة عقب اجتماع لجنة السياسة النقدية - اليوم السابع",
"description": null,
"url": "https://news.google.com/rss/articles/CBMi7gJodHRwczovL3d3dy55b3VtNy5jb20vc3RvcnkvMjAyNC8yLzEvJUQ4JUE3JUQ5JTg0JUQ4JUE4JUQ5JTg2JUQ5JTgzLSVEOCVBNyVEOSU4NCVEOSU4NSVEOCVCMSVEOSU4MyVEOCVCMiVEOSU4OS0lRDglQTclRDklODQlRDklODUlRDglQjUlRDglQjElRDklODktJUQ5JThBJUQ4JUFEJUQ4JUIzJUQ5JTg1LSVEOCVBNyVEOSU4NCVEOSU4QSVEOSU4OCVEOSU4NS0lRDglQTMlRDglQjMlRDglQjklRDglQTclRDglQjEtJUQ4JUE3JUQ5JTg0JUQ5JTgxJUQ4JUE3JUQ4JUE2JUQ4JUFGJUQ4JUE5LSVEOCVCOSVEOSU4MiVEOCVBOC0lRDglQTclRDglQUMlRDglQUElRDklODUlRDglQTclRDglQjktJUQ5JTg0JUQ4JUFDJUQ5JTg2JUQ4JUE5LzY0NjYzNTDSAeoCaHR0cHM6Ly9tLnlvdW03LmNvbS9hbXAvMjAyNC8yLzEvJUQ4JUE3JUQ5JTg0JUQ4JUE4JUQ5JTg2JUQ5JTgzLSVEOCVBNyVEOSU4NCVEOSU4NSVEOCVCMSVEOSU4MyVEOCVCMiVEOSU4OS0lRDglQTclRDklODQlRDklODUlRDglQjUlRDglQjElRDklODktJUQ5JThBJUQ4JUFEJUQ4JUIzJUQ5JTg1LSVEOCVBNyVEOSU4NCVEOSU4QSVEOSU4OCVEOSU4NS0lRDglQTMlRDglQjMlRDglQjklRDglQTclRDglQjEtJUQ4JUE3JUQ5JTg0JUQ5JTgxJUQ4JUE3JUQ4JUE2JUQ4JUFGJUQ4JUE5LSVEOCVCOSVEOSU4MiVEOCVBOC0lRDglQTclRDglQUMlRDglQUElRDklODUlRDglQTclRDglQjktJUQ5JTg0JUQ4JUFDJUQ5JTg2JUQ4JUE5LzY0NjYzNTA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T14:09:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Sky News Arabia سكاي نيوز عربية",
"title": "\"الفرصة الذهبية\".. هل اقتربنا من الاعتراف بدولة فلسطين؟ - Sky News Arabia سكاي نيوز عربية",
"description": null,
"url": "https://news.google.com/rss/articles/CBMipwJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS9taWRkbGUtZWFzdC8xNjg5OTgyLSVEOCVBNyVEOSU4NCVEOSU4MSVEOCVCMSVEOCVCNSVEOCVBOS0lRDglQTclRDklODQlRDglQjAlRDklODclRDglQTglRDklOEElRDglQTktJUQ4JUE3JUQ5JTgyJUQ4JUFBJUQ4JUIxJUQ4JUE4JUQ5JTg2JUQ4JUE3LSVEOCVBNyVEOSU4NCVEOCVBNyVEOCVCOSVEOCVBQSVEOCVCMSVEOCVBNyVEOSU4MS0lRDglQTglRDglQUYlRDklODglRDklODQlRDglQTktJUQ5JTgxJUQ5JTg0JUQ4JUIzJUQ4JUI3JUQ5JThBJUQ5JTg2JUQ4JTlG0gGrAmh0dHBzOi8vd3d3LnNreW5ld3NhcmFiaWEuY29tL2FtcC9taWRkbGUtZWFzdC8xNjg5OTgyLSVEOCVBNyVEOSU4NCVEOSU4MSVEOCVCMSVEOCVCNSVEOCVBOS0lRDglQTclRDklODQlRDglQjAlRDklODclRDglQTglRDklOEElRDglQTktJUQ4JUE3JUQ5JTgyJUQ4JUFBJUQ4JUIxJUQ4JUE4JUQ5JTg2JUQ4JUE3LSVEOCVBNyVEOSU4NCVEOCVBNyVEOCVCOSVEOCVBQSVEOCVCMSVEOCVBNyVEOSU4MS0lRDglQTglRDglQUYlRDklODglRDklODQlRDglQTktJUQ5JTgxJUQ5JTg0JUQ4JUIzJUQ4JUI3JUQ5JThBJUQ5JTg2JUQ4JTlG?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T12:57:27Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Sky News Arabia سكاي نيوز عربية",
"title": "إذا ظل التمويل معلقا.. عمليات \"أونروا\" قد تقف بهذا الموعد - Sky News Arabia سكاي نيوز عربية",
"description": null,
"url": "https://news.google.com/rss/articles/CBMiqQJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS9taWRkbGUtZWFzdC8xNjg5OTY3LSVEOCVCOCVEOSU4NC0lRDglQTclRDklODQlRDglQUElRDklODUlRDklODglRDklOEElRDklODQtJUQ5JTg1JUQ4JUI5JUQ5JTg0JUQ5JTgyJUQ4JUE3LSVEOCVCOSVEOSU4NSVEOSU4NCVEOSU4QSVEOCVBNyVEOCVBQS0lRDglQTclRDklOTQlRDklODglRDklODYlRDglQjElRDklODglRDglQTctJUQ4JUFBJUQ5JTgyJUQ5JTgxLSVEOCVBOCVEOSU4NyVEOCVCMCVEOCVBNy0lRDglQTclRDklODQlRDklODUlRDklODglRDglQjklRDglQUbSAa0CaHR0cHM6Ly93d3cuc2t5bmV3c2FyYWJpYS5jb20vYW1wL21pZGRsZS1lYXN0LzE2ODk5NjctJUQ4JUI4JUQ5JTg0LSVEOCVBNyVEOSU4NCVEOCVBQSVEOSU4NSVEOSU4OCVEOSU4QSVEOSU4NC0lRDklODUlRDglQjklRDklODQlRDklODIlRDglQTctJUQ4JUI5JUQ5JTg1JUQ5JTg0JUQ5JThBJUQ4JUE3JUQ4JUFBLSVEOCVBNyVEOSU5NCVEOSU4OCVEOSU4NiVEOCVCMSVEOSU4OCVEOCVBNy0lRDglQUElRDklODIlRDklODEtJUQ4JUE4JUQ5JTg3JUQ4JUIwJUQ4JUE3LSVEOCVBNyVEOSU4NCVEOSU4NSVEOSU4OCVEOCVCOSVEOCVBRg?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T12:24:55Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "بوابة الصبح",
"title": "\"إضافات ثورية\" مميزات تحديث iOS 17.4 من أبل وخاصية جديدة لأول مرة - بوابة الصبح",
"description": null,
"url": "https://news.google.com/rss/articles/CBMijQFodHRwczovL25ld3N5LmVsc29iNy5jb20vNDI1MjUzLyVEOSU4NSVEOSU4NSVEOSU4QSVEOCVCMiVEOCVBNyVEOCVBQS0lRDglQUElRDglQUQlRDglQUYlRDklOEElRDglQUItaW9zLTE3LTQtJUQ5JTg1JUQ5JTg2LSVEOCVBMyVEOCVBOCVEOSU4NC_SAQA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T12:20:06Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "بوابة الصبح",
"title": "رسمياً.. إطلاق هاتف Honor Magic 6 Lite بمعالج أمريكي ومزايا قوية وسعر منافس - بوابة الصبح",
"description": null,
"url": "https://news.google.com/rss/articles/CBMi5wFodHRwczovL25ld3N5LmVsc29iNy5jb20vNDI4Mzg3LyVEOCVCMSVEOCVCMyVEOSU4NSVEOSU4QSVEOCVBNyVEOSU4Qi0lRDglQTUlRDglQjclRDklODQlRDglQTclRDklODItJUQ5JTg3JUQ4JUE3JUQ4JUFBJUQ5JTgxLWhvbm9yLW1hZ2ljLTYtbGl0ZS0lRDglQTglRDklODUlRDglQjklRDglQTclRDklODQlRDglQUMtJUQ4JUEzJUQ5JTg1JUQ4JUIxJUQ5JThBJUQ5JTgzJUQ5JThBLSVEOSU4OCVEOSU4NS_SAQA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T12:19:54Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Masrawy - مصراوي",
"title": "سعر الذهب اليوم بمصر يعاود الارتفاع بمنتصف التعاملات - Masrawy - مصراوي",
"description": null,
"url": "https://news.google.com/rss/articles/CBMi2AJodHRwczovL3d3dy5tYXNyYXd5LmNvbS9uZXdzL25ld3NfZWNvbm9teS9kZXRhaWxzLzIwMjQvMi8xLzI1MzIxNTYvJUQ4JUIzJUQ4JUI5JUQ4JUIxLSVEOCVBNyVEOSU4NCVEOCVCMCVEOSU4NyVEOCVBOC0lRDglQTclRDklODQlRDklOEElRDklODglRDklODUtJUQ4JUE4JUQ5JTg1JUQ4JUI1JUQ4JUIxLSVEOSU4QSVEOCVCOSVEOCVBNyVEOSU4OCVEOCVBRi0lRDglQTclRDklODQlRDglQTclRDglQjElRDglQUElRDklODElRDglQTclRDglQjktJUQ4JUE4JUQ5JTg1JUQ5JTg2JUQ4JUFBJUQ4JUI1JUQ5JTgxLSVEOCVBNyVEOSU4NCVEOCVBQSVEOCVCOSVEOCVBNyVEOSU4NSVEOSU4NCVEOCVBNyVEOCVBQdIB3AJodHRwczovL3d3dy5tYXNyYXd5LmNvbS9uZXdzL25ld3NfZWNvbm9teS9kZXRhaWxzLzIwMjQvMi8xLzI1MzIxNTYvJUQ4JUIzJUQ4JUI5JUQ4JUIxLSVEOCVBNyVEOSU4NCVEOCVCMCVEOSU4NyVEOCVBOC0lRDglQTclRDklODQlRDklOEElRDklODglRDklODUtJUQ4JUE4JUQ5JTg1JUQ4JUI1JUQ4JUIxLSVEOSU4QSVEOCVCOSVEOCVBNyVEOSU4OCVEOCVBRi0lRDglQTclRDklODQlRDglQTclRDglQjElRDglQUElRDklODElRDglQTclRDglQjktJUQ4JUE4JUQ5JTg1JUQ5JTg2JUQ4JUFBJUQ4JUI1JUQ5JTgxLSVEOCVBNyVEOSU4NCVEOCVBQSVEOCVCOSVEOCVBNyVEOSU4NSVEOSU4NCVEOCVBNyVEOCVBQT9hbXA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T11:28:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "كووورة",
"title": "فينجادا: تصرف مانشيني غير مقبول نهائيا - كووورة",
"description": null,
"url": "https://news.google.com/rss/articles/CBMiIWh0dHBzOi8vd3d3Lmtvb29yYS5jb20vP249MTMwMzk1M9IBAA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T11:07:11Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "banker.news - موقع بانكير ",
"title": "الدولار يواصل صعوده بعد تثبيت الفائدة وتصريحات باول - banker.news - موقع بانكير ",
"description": null,
"url": "https://news.google.com/rss/articles/CBMiHWh0dHBzOi8vd3d3LmJhbmtlci5uZXdzLzY1NzM30gEA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T10:42:12Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "CNN Arabic",
"title": "بعد صور تايلور سويف المزيفة.. إيقاف المواد الإباحية بالذكاء الاصطناعي قد يكون مستحيلًا وهذا هو السبب - CNN Arabic",
"description": null,
"url": "https://news.google.com/rss/articles/CBMiX2h0dHBzOi8vYXJhYmljLmNubi5jb20vbWlzY2VsbGFuZW91cy92aWRlby8yMDI0LzAyLzAxL3YxNTEzMjctZGVlcGZha2UtYWktcGljdHVyZXMtdGF5bG9yLXN3aWZ00gFnaHR0cHM6Ly9hcmFiaWMuY25uLmNvbS9hbXBodG1sL21pc2NlbGxhbmVvdXMvdmlkZW8vMjAyNC8wMi8wMS92MTUxMzI3LWRlZXBmYWtlLWFpLXBpY3R1cmVzLXRheWxvci1zd2lmdA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T10:41:25Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "اليوم السابع",
"title": "رونالدو يغيب عن مواجهة ميسي في ودية النصر وإنتر ميامي بالسعودية - اليوم السابع",
"description": null,
"url": "https://news.google.com/rss/articles/CBMivgJodHRwczovL3d3dy55b3VtNy5jb20vc3RvcnkvMjAyNC8yLzEvJUQ4JUIxJUQ5JTg4JUQ5JTg2JUQ4JUE3JUQ5JTg0JUQ4JUFGJUQ5JTg4LSVEOSU4QSVEOCVCQSVEOSU4QSVEOCVBOC0lRDglQjklRDklODYtJUQ5JTg1JUQ5JTg4JUQ4JUE3JUQ4JUFDJUQ5JTg3JUQ4JUE5LSVEOSU4NSVEOSU4QSVEOCVCMyVEOSU4QS0lRDklODElRDklOEEtJUQ5JTg4JUQ4JUFGJUQ5JThBJUQ4JUE5LSVEOCVBNyVEOSU4NCVEOSU4NiVEOCVCNSVEOCVCMS0lRDklODglRDglQTUlRDklODYlRDglQUElRDglQjEtJUQ5JTg1JUQ5JThBJUQ4JUE3JUQ5JTg1JUQ5JThBLzY0NjYwMTDSAboCaHR0cHM6Ly9tLnlvdW03LmNvbS9hbXAvMjAyNC8yLzEvJUQ4JUIxJUQ5JTg4JUQ5JTg2JUQ4JUE3JUQ5JTg0JUQ4JUFGJUQ5JTg4LSVEOSU4QSVEOCVCQSVEOSU4QSVEOCVBOC0lRDglQjklRDklODYtJUQ5JTg1JUQ5JTg4JUQ4JUE3JUQ4JUFDJUQ5JTg3JUQ4JUE5LSVEOSU4NSVEOSU4QSVEOCVCMyVEOSU4QS0lRDklODElRDklOEEtJUQ5JTg4JUQ4JUFGJUQ5JThBJUQ4JUE5LSVEOCVBNyVEOSU4NCVEOSU4NiVEOCVCNSVEOCVCMS0lRDklODglRDglQTUlRDklODYlRDglQUElRDglQjEtJUQ5JTg1JUQ5JThBJUQ4JUE3JUQ5JTg1JUQ5JThBLzY0NjYwMTA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T10:39:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Sky News Arabia سكاي نيوز عربية",
"title": "صحيفة تحذر: جبهة إسرائيل الشمالية تقترب من نقطة \"اللا عودة\" - Sky News Arabia سكاي نيوز عربية",
"description": null,
"url": "https://news.google.com/rss/articles/CBMi1AJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS9taWRkbGUtZWFzdC8xNjg5OTMxLSVEOCVCNSVEOCVBRCVEOSU4QSVEOSU4MSVEOCVBOS0lRDglQUElRDglQUQlRDglQjAlRDglQjEtJUQ4JUFDJUQ4JUE4JUQ5JTg3JUQ4JUE5LSVEOCVBNyVEOSU5NSVEOCVCMyVEOCVCMSVEOCVBNyVEOSU4QSVEOSU5NCVEOSU4QSVEOSU4NC0lRDglQTclRDklODQlRDglQjQlRDklODUlRDglQTclRDklODQlRDklOEElRDglQTktJUQ4JUFBJUQ5JTgyJUQ4JUFBJUQ4JUIxJUQ4JUE4LSVEOSU4NiVEOSU4MiVEOCVCNyVEOCVBOS0lRDglQTclRDklODQlRDklODQlRDglQTctJUQ4JUI5JUQ5JTg4JUQ4JUFGJUQ4JUE50gHYAmh0dHBzOi8vd3d3LnNreW5ld3NhcmFiaWEuY29tL2FtcC9taWRkbGUtZWFzdC8xNjg5OTMxLSVEOCVCNSVEOCVBRCVEOSU4QSVEOSU4MSVEOCVBOS0lRDglQUElRDglQUQlRDglQjAlRDglQjEtJUQ4JUFDJUQ4JUE4JUQ5JTg3JUQ4JUE5LSVEOCVBNyVEOSU5NSVEOCVCMyVEOCVCMSVEOCVBNyVEOSU4QSVEOSU5NCVEOSU4QSVEOSU4NC0lRDglQTclRDklODQlRDglQjQlRDklODUlRDglQTclRDklODQlRDklOEElRDglQTktJUQ4JUFBJUQ5JTgyJUQ4JUFBJUQ4JUIxJUQ4JUE4LSVEOSU4NiVEOSU4MiVEOCVCNyVEOCVBOS0lRDglQTclRDklODQlRDklODQlRDglQTctJUQ4JUI5JUQ5JTg4JUQ4JUFGJUQ4JUE5?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T10:36:17Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "beIN SPORTS",
"title": "منتخب سوريا: مكاسب رغم الخروج الحزين...الآن بدأ الحلم - beIN SPORTS",
"description": null,
"url": "https://news.google.com/rss/articles/CBMi5gNodHRwczovL3d3dy5iZWluc3BvcnRzLmNvbS9hci1tZW5hLyVEOSU4MyVEOCVCMSVEOCVBOS0lRDglQTclRDklODQlRDklODIlRDglQUYlRDklODUvJUQ5JTgzJUQ4JUEzJUQ4JUIzLSVEOCVBMiVEOCVCMyVEOSU4QSVEOCVBNy8lRDglQTclRDklODQlRDglQTMlRDglQUUlRDglQTglRDglQTclRDglQjEtJUQ4JUE3JUQ5JTg0JUQ5JTgxJUQ5JThBJUQ4JUFGJUQ5JThBJUQ5JTg4LyVEOSU4NSVEOSU4NiVEOCVBQSVEOCVBRSVEOCVBOC0lRDglQjMlRDklODglRDglQjElRDklOEElRDglQTctJUQ5JTg1JUQ5JTgzJUQ4JUE3JUQ4JUIzJUQ4JUE4LSVEOCVCMSVEOCVCQSVEOSU4NS0lRDglQTclRDklODQlRDglQUUlRDglQjElRDklODglRDglQUMtJUQ4JUE3JUQ5JTg0JUQ4JUFEJUQ4JUIyJUQ5JThBJUQ5JTg2LSVEOCVBNyVEOSU4NCVEOCVBMiVEOSU4Ni0lRDglQTglRDglQUYlRDglQTMtJUQ4JUE3JUQ5JTg0JUQ4JUFEJUQ5JTg0JUQ5JTg1LTIwMjQtMDItMDHSAQA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T10:13:48Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "العربية",
"title": "يتجه نحونا بسرعة هائلة.. كويكب يضرب الأرض في هذا الموعد - العربية",
"description": null,
"url": "https://news.google.com/rss/articles/CBMivgJodHRwczovL3d3dy5hbGFyYWJpeWEubmV0L3NjaWVuY2UvMjAyNC8wMi8wMS8lRDklOEElRDglQUElRDglQUMlRDklODctJUQ5JTg2JUQ4JUFEJUQ5JTg4JUQ5JTg2JUQ4JUE3LSVEOCVBOCVEOCVCMyVEOCVCMSVEOCVCOSVEOCVBOS0lRDklODclRDglQTclRDglQTYlRDklODQlRDglQTktJUQ5JTgzJUQ5JTg4JUQ5JThBJUQ5JTgzJUQ4JUE4LSVEOSU4QSVEOCVCNiVEOCVCMSVEOCVBOC0lRDglQTclRDklODQlRDglQTMlRDglQjElRDglQjYtJUQ5JTgxJUQ5JThBLSVEOSU4NyVEOCVCMCVEOCVBNy0lRDglQTclRDklODQlRDklODUlRDklODglRDglQjklRDglQUbSAcICaHR0cHM6Ly93d3cuYWxhcmFiaXlhLm5ldC9hbXAvc2NpZW5jZS8yMDI0LzAyLzAxLyVEOSU4QSVEOCVBQSVEOCVBQyVEOSU4Ny0lRDklODYlRDglQUQlRDklODglRDklODYlRDglQTctJUQ4JUE4JUQ4JUIzJUQ4JUIxJUQ4JUI5JUQ4JUE5LSVEOSU4NyVEOCVBNyVEOCVBNiVEOSU4NCVEOCVBOS0lRDklODMlRDklODglRDklOEElRDklODMlRDglQTgtJUQ5JThBJUQ4JUI2JUQ4JUIxJUQ4JUE4LSVEOCVBNyVEOSU4NCVEOCVBMyVEOCVCMSVEOCVCNi0lRDklODElRDklOEEtJUQ5JTg3JUQ4JUIwJUQ4JUE3LSVEOCVBNyVEOSU4NCVEOSU4NSVEOSU4OCVEOCVCOSVEOCVBRg?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T09:51:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Masrawy - مصراوي",
"title": "بالأرقام.. تفاصيل عقد عبدالله السعيد مع الزمالك - Masrawy - مصراوي",
"description": null,
"url": "https://news.google.com/rss/articles/CBMitAJodHRwczovL3d3dy5tYXNyYXd5LmNvbS9zcG9ydHMvc3BvcnRzX25ld3MvZGV0YWlscy8yMDI0LzIvMS8yNTMyMDg2LyVEOCVBOCVEOCVBNyVEOSU4NCVEOCVBMyVEOCVCMSVEOSU4MiVEOCVBNyVEOSU4NS0lRDglQUElRDklODElRDglQTclRDglQjUlRDklOEElRDklODQtJUQ4JUI5JUQ5JTgyJUQ4JUFGLSVEOCVCOSVEOCVBOCVEOCVBRiVEOCVBNyVEOSU4NCVEOSU4NCVEOSU4Ny0lRDglQTclRDklODQlRDglQjMlRDglQjklRDklOEElRDglQUYtJUQ5JTg1JUQ4JUI5LSVEOCVBNyVEOSU4NCVEOCVCMiVEOSU4NSVEOCVBNyVEOSU4NCVEOSU4M9IBuAJodHRwczovL3d3dy5tYXNyYXd5LmNvbS9zcG9ydHMvc3BvcnRzX25ld3MvZGV0YWlscy8yMDI0LzIvMS8yNTMyMDg2LyVEOCVBOCVEOCVBNyVEOSU4NCVEOCVBMyVEOCVCMSVEOSU4MiVEOCVBNyVEOSU4NS0lRDglQUElRDklODElRDglQTclRDglQjUlRDklOEElRDklODQtJUQ4JUI5JUQ5JTgyJUQ4JUFGLSVEOCVCOSVEOCVBOCVEOCVBRiVEOCVBNyVEOSU4NCVEOSU4NCVEOSU4Ny0lRDglQTclRDklODQlRDglQjMlRDglQjklRDklOEElRDglQUYtJUQ5JTg1JUQ4JUI5LSVEOCVBNyVEOSU4NCVEOCVCMiVEOSU4NSVEOCVBNyVEOSU4NCVEOSU4Mz9hbXA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T09:40:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "اليوم السابع",
"title": "فيلم \"رحلة 404\" لمنى زكى يحصد 7.3 مليون جنيه في منذ عرضه السينمات المختلفة - اليوم السابع",
"description": null,
"url": "https://news.google.com/rss/articles/CBMi4wFodHRwczovL3d3dy55b3VtNy5jb20vc3RvcnkvMjAyNC8yLzEvJUQ5JTgxJUQ5JThBJUQ5JTg0JUQ5JTg1LSVEOCVCMSVEOCVBRCVEOSU4NCVEOCVBOS00MDQtJUQ5JTg0JUQ5JTg1JUQ5JTg2JUQ5JTg5LSVEOCVCMiVEOSU4MyVEOSU4OS0lRDklOEElRDglQUQlRDglQjUlRDglQUYtNy0zLSVEOSU4NSVEOSU4NCVEOSU4QSVEOSU4OCVEOSU4Ni0lRDglQUMlRDklODYlRDklOEElRDklODcvNjQ2NTkwMNIB3wFodHRwczovL20ueW91bTcuY29tL2FtcC8yMDI0LzIvMS8lRDklODElRDklOEElRDklODQlRDklODUtJUQ4JUIxJUQ4JUFEJUQ5JTg0JUQ4JUE5LTQwNC0lRDklODQlRDklODUlRDklODYlRDklODktJUQ4JUIyJUQ5JTgzJUQ5JTg5LSVEOSU4QSVEOCVBRCVEOCVCNSVEOCVBRi03LTMtJUQ5JTg1JUQ5JTg0JUQ5JThBJUQ5JTg4JUQ5JTg2LSVEOCVBQyVEOSU4NiVEOSU4QSVEOSU4Ny82NDY1OTAw?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T09:31:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "الحرة",
"title": "\"أديداس\" تكشف تأثرها بأحداث البحر الأحمر - الحرة",
"description": null,
"url": "https://news.google.com/rss/articles/CBMihwJodHRwczovL3d3dy5hbGh1cnJhLmNvbS9hcmFiaWMtYW5kLWludGVybmF0aW9uYWwvMjAyNC8wMi8wMS8lRDglQTMlRDglQUYlRDklOEElRDglQUYlRDglQTclRDglQjMtJUQ4JUFBJUQ5JTgzJUQ4JUI0JUQ5JTgxLSVEOCVBQSVEOCVBMyVEOCVBQiVEOCVCMSVEOSU4NyVEOCVBNy0lRDglQTglRDglQTMlRDglQUQlRDglQUYlRDglQTclRDglQUItJUQ4JUE3JUQ5JTg0JUQ4JUE4JUQ4JUFEJUQ4JUIxLSVEOCVBNyVEOSU4NCVEOCVBMyVEOCVBRCVEOSU4NSVEOCVCMdIBiwJodHRwczovL3d3dy5hbGh1cnJhLmNvbS9hcmFiaWMtYW5kLWludGVybmF0aW9uYWwvMjAyNC8wMi8wMS8lRDglQTMlRDglQUYlRDklOEElRDglQUYlRDglQTclRDglQjMtJUQ4JUFBJUQ5JTgzJUQ4JUI0JUQ5JTgxLSVEOCVBQSVEOCVBMyVEOCVBQiVEOCVCMSVEOSU4NyVEOCVBNy0lRDglQTglRDglQTMlRDglQUQlRDglQUYlRDglQTclRDglQUItJUQ4JUE3JUQ5JTg0JUQ4JUE4JUQ4JUFEJUQ4JUIxLSVEOCVBNyVEOSU4NCVEOCVBMyVEOCVBRCVEOSU4NSVEOCVCMT9hbXA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T09:30:07Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "اليوم السابع",
"title": "تعليم القاهرة تعرض نتيجة الصف الثالث الإعدادى الترم الأول بالمدارس - اليوم السابع",
"description": null,
"url": "https://news.google.com/rss/articles/CBMijANodHRwczovL3d3dy55b3VtNy5jb20vc3RvcnkvMjAyNC8yLzEvJUQ4JUFBJUQ4JUI5JUQ5JTg0JUQ5JThBJUQ5JTg1LSVEOCVBNyVEOSU4NCVEOSU4MiVEOCVBNyVEOSU4NyVEOCVCMSVEOCVBOS0lRDglQUElRDglQjklRDglQjElRDglQjYtJUQ5JTg2JUQ4JUFBJUQ5JThBJUQ4JUFDJUQ4JUE5LSVEOCVBNyVEOSU4NCVEOCVCNSVEOSU4MS0lRDglQTclRDklODQlRDglQUIlRDglQTclRDklODQlRDglQUItJUQ4JUE3JUQ5JTg0JUQ4JUE1JUQ4JUI5JUQ4JUFGJUQ4JUE3JUQ4JUFGJUQ5JTg5LSVEOCVBNyVEOSU4NCVEOCVBQSVEOCVCMSVEOSU4NS0lRDglQTclRDklODQlRDglQTMlRDklODglRDklODQtJUQ4JUE4JUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ4JUFGJUQ4JUE3JUQ4JUIxJUQ4JUIzLzY0NjU5MjTSAYgDaHR0cHM6Ly9tLnlvdW03LmNvbS9hbXAvMjAyNC8yLzEvJUQ4JUFBJUQ4JUI5JUQ5JTg0JUQ5JThBJUQ5JTg1LSVEOCVBNyVEOSU4NCVEOSU4MiVEOCVBNyVEOSU4NyVEOCVCMSVEOCVBOS0lRDglQUElRDglQjklRDglQjElRDglQjYtJUQ5JTg2JUQ4JUFBJUQ5JThBJUQ4JUFDJUQ4JUE5LSVEOCVBNyVEOSU4NCVEOCVCNSVEOSU4MS0lRDglQTclRDklODQlRDglQUIlRDglQTclRDklODQlRDglQUItJUQ4JUE3JUQ5JTg0JUQ4JUE1JUQ4JUI5JUQ4JUFGJUQ4JUE3JUQ4JUFGJUQ5JTg5LSVEOCVBNyVEOSU4NCVEOCVBQSVEOCVCMSVEOSU4NS0lRDglQTclRDklODQlRDglQTMlRDklODglRDklODQtJUQ4JUE4JUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ4JUFGJUQ4JUE3JUQ4JUIxJUQ4JUIzLzY0NjU5MjQ?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T09:30:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Sky News Arabia سكاي نيوز عربية",
"title": "ترامب وبايدن يتبادلون \"اللكمات\".. من المسؤول عن أفعال إيران؟ - Sky News Arabia سكاي نيوز عربية",
"description": null,
"url": "https://news.google.com/rss/articles/CBMizAJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS93b3JsZC8xNjg5ODk3LSVEOCVBQSVEOCVCMSVEOCVBNyVEOSU4NSVEOCVBOC0lRDklODglRDglQTglRDglQTclRDklOEElRDglQUYlRDklODYtJUQ5JThBJUQ4JUFBJUQ4JUE4JUQ4JUE3JUQ4JUFGJUQ5JTg0JUQ5JTg4JUQ5JTg2LSVEOCVBNyVEOSU4NCVEOSU4NCVEOSU4MyVEOSU4NSVEOCVBNyVEOCVBQS0lRDglQTclRDklODQlRDklODUlRDglQjMlRDklODglRDklOTQlRDklODglRDklODQtJUQ4JUE3JUQ5JTk0JUQ5JTgxJUQ4JUI5JUQ4JUE3JUQ5JTg0LSVEOCVBNyVEOSU5NSVEOSU4QSVEOCVCMSVEOCVBNyVEOSU4NiVEOCU5RtIB0AJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS9hbXAvd29ybGQvMTY4OTg5Ny0lRDglQUElRDglQjElRDglQTclRDklODUlRDglQTgtJUQ5JTg4JUQ4JUE4JUQ4JUE3JUQ5JThBJUQ4JUFGJUQ5JTg2LSVEOSU4QSVEOCVBQSVEOCVBOCVEOCVBNyVEOCVBRiVEOSU4NCVEOSU4OCVEOSU4Ni0lRDglQTclRDklODQlRDklODQlRDklODMlRDklODUlRDglQTclRDglQUEtJUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ4JUIzJUQ5JTg4JUQ5JTk0JUQ5JTg4JUQ5JTg0LSVEOCVBNyVEOSU5NCVEOSU4MSVEOCVCOSVEOCVBNyVEOSU4NC0lRDglQTclRDklOTUlRDklOEElRDglQjElRDglQTclRDklODYlRDglOUY?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T09:10:25Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Masrawy - مصراوي",
"title": "بلومبرج: مصر تتفاوض مع صندوق النقد على اتفاق قد يتخطى 10 مليارات دولار - Masrawy - مصراوي",
"description": null,
"url": "https://news.google.com/rss/articles/CBMimwNodHRwczovL3d3dy5tYXNyYXd5LmNvbS9uZXdzL25ld3NfZWNvbm9teS9kZXRhaWxzLzIwMjQvMi8xLzI1MzIwNTEvJUQ4JUE4JUQ5JTg0JUQ5JTg4JUQ5JTg1JUQ4JUE4JUQ4JUIxJUQ4JUFDLSVEOSU4NSVEOCVCNSVEOCVCMS0lRDglQUElRDglQUElRDklODElRDglQTclRDklODglRDglQjYtJUQ5JTg1JUQ4JUI5LSVEOCVCNSVEOSU4NiVEOCVBRiVEOSU4OCVEOSU4Mi0lRDglQTclRDklODQlRDklODYlRDklODIlRDglQUYtJUQ4JUI5JUQ5JTg0JUQ5JTg5LSVEOCVBNyVEOCVBQSVEOSU4MSVEOCVBNyVEOSU4Mi0lRDklODIlRDglQUYtJUQ5JThBJUQ4JUFBJUQ4JUFFJUQ4JUI3JUQ5JTg5LTEwLSVEOSU4NSVEOSU4NCVEOSU4QSVEOCVBNyVEOCVCMSVEOCVBNyVEOCVBQS0lRDglQUYlRDklODglRDklODQlRDglQTclRDglQjHSAZ8DaHR0cHM6Ly93d3cubWFzcmF3eS5jb20vbmV3cy9uZXdzX2Vjb25vbXkvZGV0YWlscy8yMDI0LzIvMS8yNTMyMDUxLyVEOCVBOCVEOSU4NCVEOSU4OCVEOSU4NSVEOCVBOCVEOCVCMSVEOCVBQy0lRDklODUlRDglQjUlRDglQjEtJUQ4JUFBJUQ4JUFBJUQ5JTgxJUQ4JUE3JUQ5JTg4JUQ4JUI2LSVEOSU4NSVEOCVCOS0lRDglQjUlRDklODYlRDglQUYlRDklODglRDklODItJUQ4JUE3JUQ5JTg0JUQ5JTg2JUQ5JTgyJUQ4JUFGLSVEOCVCOSVEOSU4NCVEOSU4OS0lRDglQTclRDglQUElRDklODElRDglQTclRDklODItJUQ5JTgyJUQ4JUFGLSVEOSU4QSVEOCVBQSVEOCVBRSVEOCVCNyVEOSU4OS0xMC0lRDklODUlRDklODQlRDklOEElRDglQTclRDglQjElRDglQTclRDglQUEtJUQ4JUFGJUQ5JTg4JUQ5JTg0JUQ4JUE3JUQ4JUIxP2FtcA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T08:48:00Z",
"content": null
},
-{
-"source": {
"id": "google-news",
"name": "Google News"
},
"author": "Masrawy - مصراوي",
"title": "مشاركين بمفاوضات تبادل الأسرى: تصريحات نتنياهو مضرة وربما يسعى لإفشال الصفقة - Masrawy - مصراوي",
"description": null,
"url": "https://news.google.com/rss/articles/CBMitANodHRwczovL3d3dy5tYXNyYXd5LmNvbS9uZXdzL25ld3NfcHVibGljYWZmYWlycy9kZXRhaWxzLzIwMjQvMi8xLzI1MzIwMzAvJUQ5JTg1JUQ4JUI0JUQ4JUE3JUQ4JUIxJUQ5JTgzJUQ5JThBJUQ5JTg2LSVEOCVBOCVEOSU4NSVEOSU4MSVEOCVBNyVEOSU4OCVEOCVCNiVEOCVBNyVEOCVBQS0lRDglQUElRDglQTglRDglQTclRDglQUYlRDklODQtJUQ4JUE3JUQ5JTg0JUQ4JUEzJUQ4JUIzJUQ4JUIxJUQ5JTg5LSVEOCVBQSVEOCVCNSVEOCVCMSVEOSU4QSVEOCVBRCVEOCVBNyVEOCVBQS0lRDklODYlRDglQUElRDklODYlRDklOEElRDglQTclRDklODclRDklODgtJUQ5JTg1JUQ4JUI2JUQ4JUIxJUQ4JUE5LSVEOSU4OCVEOCVCMSVEOCVBOCVEOSU4NSVEOCVBNy0lRDklOEElRDglQjMlRDglQjklRDklODktJUQ5JTg0JUQ4JUE1JUQ5JTgxJUQ4JUI0JUQ4JUE3JUQ5JTg00gHdA2h0dHBzOi8vd3d3Lm1hc3Jhd3kuY29tL25ld3MvbmV3c19wdWJsaWNhZmZhaXJzL2RldGFpbHMvMjAyNC8yLzEvMjUzMjAzMC8lRDklODUlRDglQjQlRDglQTclRDglQjElRDklODMlRDklOEElRDklODYtJUQ4JUE4JUQ5JTg1JUQ5JTgxJUQ4JUE3JUQ5JTg4JUQ4JUI2JUQ4JUE3JUQ4JUFBLSVEOCVBQSVEOCVBOCVEOCVBNyVEOCVBRiVEOSU4NC0lRDglQTclRDklODQlRDglQTMlRDglQjMlRDglQjElRDklODktJUQ4JUFBJUQ4JUI1JUQ4JUIxJUQ5JThBJUQ4JUFEJUQ4JUE3JUQ4JUFBLSVEOSU4NiVEOCVBQSVEOSU4NiVEOSU4QSVEOCVBNyVEOSU4NyVEOSU4OC0lRDklODUlRDglQjYlRDglQjElRDglQTktJUQ5JTg4JUQ4JUIxJUQ4JUE4JUQ5JTg1JUQ4JUE3LSVEOSU4QSVEOCVCMyVEOCVCOSVEOSU4OS0lRDklODQlRDglQTUlRDklODElRDglQjQlRDglQTclRDklODQtJUQ4JUE3JUQ5JTg0JUQ4JUI1JUQ5JTgxJUQ5JTgyJUQ4JUE5P2FtcA?oc=5",
"urlToImage": null,
"publishedAt": "2024-02-01T08:06:00Z",
"content": null
}
]
}*/